name: ifalw

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Skipped job
    # if: false
    steps:
      - run: echo "I am skipped"
      - run: exit 1
  job2:
    runs-on: ubuntu-latest
    name: Mustn't be skipped
    needs: [job1]
    if: ${{ always() || true }}
    # if: true
    steps:
      - run: echo "I should have been displayed"
      - run: echo job1out1 is ${{needs.job1.outputs.output1}}
